---
  - hosts: all
    remote_user: user
    become: yes
    become_method: sudo

    tasks:
      - apt:
          name: nginx
          state: present
          update_cache: yes
      - service:
          name: nginx
          state: started

      - name: Nginx config
        template:
           src: /home/aniskin/terraform-yandex/ansible-nginx/nginx.conf.j2
           dest: /etc/nginx/sites-available/default

      - name: Enable config
        file:
           src: /etc/nginx/sites-available/default
           dest: /etc/nginx/sites-enabled/default
           state: link
                 
      - service:
          name: nginx
          state: restarted
